# blah: 
	# cc blah.c -o blah
# The firs time make is run the compilation will take place
# however if we modify the blah.c and make again then make 
# will output make: 'blah is up to date'

# to avoid this we add the blah.c to the depencencies

blah: blah.c
	cc blah.c -o blah

# Remember blah will always run if blah file doesn't exist or blah.c is newer then blah

