#add -k when running make to continue running even if a error arises. helpfuul to seee all error at one 

# add - before a command to suppress the error

# add -i to make all error suppressed

one:
	# This error will be printed but ignores
	-false
	echo "hi" 
	treu
	echo "bye"
	fal
